import { useEffect, useState, type FormEvent } from 'react';
import { ArrowLeft, CalendarDays, LogOut, Pencil, Plus, RefreshCw, Save, Trash2 } from 'lucide-react';
import { Link, Route, Switch, useLocation } from 'wouter';

type MasterEvent = {
  id: string; title: string; event_date: string; start_time: string; status: string; seats: number | null;
  description: string; system: string; format: string; location: string; duration: string; price: string;
  experience: string; age: string; player_prep: string; recurrence: string; recurrence_until: string | null;
  archived: boolean; revision: number;
};
type FormState = Omit<MasterEvent, 'id' | 'archived' | 'revision'>;
type Session = { user: { id: string; login: string; role: string }; csrfToken?: string };
const emptyForm: FormState = { title: '', event_date: '', start_time: '', status: 'available', seats: null, description: '', system: '', format: 'online', location: '', duration: '', price: '', experience: '', age: '18+', player_prep: '', recurrence: 'none', recurrence_until: null };

async function api<T>(path: string, init: RequestInit = {}) {
  const response = await fetch(path, { ...init, credentials: 'include', headers: { Accept: 'application/json', ...(init.body ? { 'Content-Type': 'application/json' } : {}), ...(init.headers ?? {}) } });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(typeof data.error === 'string' ? data.error : 'Не удалось выполнить запрос.');
  return data as T;
}

function LoginPage() {
  const [, navigate] = useLocation(); const [login, setLogin] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [pending, setPending] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setPending(true); setError(''); try { await api('/api/auth/login', { method: 'POST', body: JSON.stringify({ login, password }) }); navigate('/master/calendar'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Не удалось войти.'); } finally { setPending(false); } }
  return <main className="master-shell"><section className="master-login"><Link className="master-back" href="/"><ArrowLeft size={15} /> На сайт</Link><span className="eyebrow">закрытая зона мастера</span><h1>Кабинет<br /><em>Никс</em></h1><p>Здесь можно вести календарь и видеть заявки игроков. Публичный сайт остаётся на этом же домене.</p><form onSubmit={submit} className="master-card"><label>Логин<input value={login} onChange={(event) => setLogin(event.target.value)} autoComplete="username" required /></label><label>Пароль<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="current-password" required /></label>{error && <div className="master-error" role="alert">{error}</div>}<button className="button button-primary" disabled={pending}>{pending ? 'Проверяю…' : 'Войти'}</button></form></section></main>;
}

function MasterLayout({ session, children }: { session: Session; children: React.ReactNode }) {
  const [, navigate] = useLocation();
  async function logout() { await api('/api/auth/logout', { method: 'POST' }).catch(() => undefined); navigate('/master/login'); }
  return <main className="master-shell"><div className="master-topbar"><Link className="brand" href="/master/calendar"><span className="brand-mark">N</span><span>МАДМУАЗЕЛЬ НИКС</span></Link><div className="master-user"><span>{session.user.login}</span><button type="button" onClick={logout} aria-label="Выйти"><LogOut size={15} /></button></div></div><div className="master-nav"><Link href="/master/calendar"><CalendarDays size={15} /> Календарь</Link><Link href="/master/applications">Заявки</Link><Link href="/"><ArrowLeft size={14} /> На сайт</Link></div>{children}</main>;
}

function EventEditor({ event, session, onSaved, onCancel }: { event: MasterEvent | null; session: Session; onSaved: () => void; onCancel: () => void }) {
  const [form, setForm] = useState<FormState>(event ? { title: event.title, event_date: event.event_date, start_time: event.start_time, status: event.status, seats: event.seats, description: event.description, system: event.system, format: event.format, location: event.location, duration: event.duration, price: event.price, experience: event.experience, age: event.age, player_prep: event.player_prep, recurrence: event.recurrence, recurrence_until: event.recurrence_until } : emptyForm);
  const [error, setError] = useState(''); const set = (key: keyof FormState, value: string | number | null) => setForm((current) => ({ ...current, [key]: value }));
  async function submit(eventObject: FormEvent) { eventObject.preventDefault(); setError(''); const payload = { ...form, playerPrep: form.player_prep, eventDate: form.event_date, startTime: form.start_time, recurrenceUntil: form.recurrence_until, seats: form.seats === null || form.seats === '' ? null : Number(form.seats) }; try { await api(event ? `/api/master/events/${event.id}` : '/api/master/events', { method: event ? 'PATCH' : 'POST', headers: { 'X-CSRF-Token': session.csrfToken ?? '' }, body: JSON.stringify(event ? { ...payload, revision: event.revision } : payload) }); onSaved(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Не удалось сохранить игру.'); } }
  return <form className="master-editor" onSubmit={submit}><div className="master-editor-head"><div><span className="eyebrow">{event ? 'редактирование' : 'новая запись'}</span><h2>{event ? 'Изменить игру' : 'Добавить игру'}</h2></div><button type="button" className="master-icon-button" onClick={onCancel} aria-label="Закрыть">×</button></div><div className="master-fields"><label>Название<input value={form.title} onChange={(e) => set('title', e.target.value)} required /></label><label>Дата<input type="date" value={form.event_date} onChange={(e) => set('event_date', e.target.value)} required /></label><label>Время<input type="time" value={form.start_time} onChange={(e) => set('start_time', e.target.value)} /></label><label>Статус<select value={form.status} onChange={(e) => set('status', e.target.value)}><option value="available">Открыта</option><option value="waiting">Лист ожидания</option><option value="closed">Закрыта</option><option value="ongoing">Кампания идёт</option><option value="day_off">Выходной</option><option value="children_group">Детская группа</option><option value="open_slot">Свободный слот</option></select></label><label>Свободных мест<input type="number" min="0" value={form.seats ?? ''} onChange={(e) => set('seats', e.target.value === '' ? null : Number(e.target.value))} /></label><label>Повторение<select value={form.recurrence} onChange={(e) => set('recurrence', e.target.value)}><option value="none">Без повторения</option><option value="daily">Каждый день</option><option value="weekly">Каждую неделю</option><option value="biweekly">Раз в две недели</option><option value="monthly">Каждый месяц</option></select></label><label>Повторять до<input type="date" value={form.recurrence_until ?? ''} onChange={(e) => set('recurrence_until', e.target.value || null)} /></label><label>Система<input value={form.system} onChange={(e) => set('system', e.target.value)} placeholder="D&D 5e" /></label><label>Формат<select value={form.format} onChange={(e) => set('format', e.target.value)}><option value="online">Онлайн</option><option value="offline">Очно</option></select></label><label>Место<input value={form.location} onChange={(e) => set('location', e.target.value)} /></label><label>Цена<input value={form.price} onChange={(e) => set('price', e.target.value)} placeholder="1500 ₽" /></label><label>Возраст<input value={form.age} onChange={(e) => set('age', e.target.value)} /></label><label className="full">Описание<textarea value={form.description} onChange={(e) => set('description', e.target.value)} rows={4} /></label><label className="full">Для игроков<textarea value={form.player_prep} onChange={(e) => set('player_prep', e.target.value)} rows={3} /></label></div>{error && <div className="master-error" role="alert">{error}</div>}<div className="master-editor-actions"><button type="button" className="button button-ghost" onClick={onCancel}>Отменить</button><button className="button button-primary"><Save size={15} /> Сохранить</button></div></form>;
}

function CalendarPage({ session }: { session: Session }) {
  const [events, setEvents] = useState<MasterEvent[]>([]); const [editing, setEditing] = useState<MasterEvent | null | undefined>(undefined); const [error, setError] = useState('');
  const load = () => api<{ events: MasterEvent[] }>('/api/master/events').then((data) => setEvents(data.events)).catch((reason) => setError(reason instanceof Error ? reason.message : 'Не удалось загрузить календарь.'));
  useEffect(() => { load(); }, []);
  async function remove(event: MasterEvent) { if (!window.confirm(`Убрать игру «${event.title}» из календаря?`)) return; try { await api(`/api/master/events/${event.id}`, { method: 'DELETE', headers: { 'X-CSRF-Token': session.csrfToken ?? '' } }); load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Не удалось удалить игру.'); } }
  return <MasterLayout session={session}><section className="master-content"><div className="master-heading"><div><span className="eyebrow">расписание</span><h1>Календарь<br /><em>игр</em></h1></div><button className="button button-primary" onClick={() => setEditing(null)}><Plus size={16} /> Добавить игру</button></div>{error && <div className="master-error">{error}</div>}<div className="master-toolbar"><span>Все записи: {events.filter((event) => !event.archived).length}</span><button type="button" onClick={load}><RefreshCw size={14} /> Обновить</button></div><div className="master-events">{events.filter((event) => !event.archived).map((event) => <article className="master-event-card" key={event.id}><div className="master-event-date"><strong>{event.event_date.slice(8)}</strong><span>{event.event_date.slice(0, 7)}</span></div><div className="master-event-info"><span className="master-status">{event.status}</span><h2>{event.title || 'Без названия'}</h2><p>{event.start_time || 'Время не указано'} · {event.system || 'Система не указана'} · {event.format || 'Формат не указан'}</p></div><div className="master-event-actions"><button type="button" onClick={() => setEditing(event)} aria-label="Редактировать"><Pencil size={15} /></button><button type="button" onClick={() => remove(event)} aria-label="Удалить"><Trash2 size={15} /></button></div></article>)}{!events.length && <div className="master-empty">Календарь пока пуст. Добавьте первую игру.</div>}</div></section>{editing !== undefined && <div className="master-overlay"><EventEditor event={editing} session={session} onSaved={() => { setEditing(undefined); load(); }} onCancel={() => setEditing(undefined)} /></div>}</MasterLayout>;
}

function ApplicationsPage({ session }: { session: Session }) { const [applications, setApplications] = useState<any[]>([]); useEffect(() => { api<{ applications: any[] }>('/api/master/applications').then((data) => setApplications(data.applications)).catch(() => undefined); }, []); return <MasterLayout session={session}><section className="master-content"><div className="master-heading"><div><span className="eyebrow">входящие</span><h1>Заявки<br /><em>игроков</em></h1></div></div><div className="master-applications">{applications.map((item) => <article className="master-application" key={item.id}><div><span>{new Date(item.created_at).toLocaleString('ru-RU')}</span><h2>{item.name}</h2><a href={`https://t.me/${String(item.contact).replace(/^@/, '')}`} target="_blank" rel="noreferrer">{item.contact}</a></div><p>{item.wishes || item.system || 'Без дополнительных пожеланий'}</p><strong>{item.players} игроков</strong></article>)}{!applications.length && <div className="master-empty">Новых заявок пока нет.</div>}</div></section></MasterLayout>; }

export default function MasterRoutes() { const [session, setSession] = useState<Session | null>(null); const [, navigate] = useLocation(); useEffect(() => { api<Session>('/api/auth/me').then(setSession).catch(() => setSession(null)); }, []); if (!session) return <Switch><Route path="/master/login" component={LoginPage} /><Route><LoginPage /></Route></Switch>; return <Switch><Route path="/master/calendar"><CalendarPage session={session} /></Route><Route path="/master/applications"><ApplicationsPage session={session} /></Route><Route><CalendarPage session={session} /></Route></Switch>; }
